Fix `hack/eks/install.sh` and add server auth mod for Argo (#549)
- Fix ingress controller Helm chart path
- Gateway Ingress was manged by public ingress controller, where the entry in Route 53 is hard-coded to the internal ELB. The reason was the lack of `gateway.ingress.annotations.class=capact` override during install.
- Add missing region to aws CLI
- Bump EKS version to be compatible with Capact. Currently, you will get such error:
    ```bash
     ✗ Installing capact Helm chart
    Error: All attempts fail:
    #1: while installing Helm chart [capact]: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
    #2: while installing Helm chart [capact]: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
    #3: while installing Helm chart [capact]: unable to build kubernetes objects from release manifest: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1"
    ```
- The Argo server used to start with auth mode of "server" by default, but since v3.0 it defaults to the "client". As a result, you need to always pass the token (first generate it via SA). I changed it back to `server` as we don't expose Argo publically.